DROP TABLE IF EXISTS projekty.login CASCADE;
CREATE TABLE projekty.login
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.login_roles CASCADE;
CREATE TABLE projekty.login_roles
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login_id BIGINT NOT NULL,
    role_id  BIGINT NOT NULL,
    CONSTRAINT pk_login_roles PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.projekty CASCADE;
CREATE TABLE projekty.projekty
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submission_date TIMESTAMP WITHOUT TIME ZONE,
    deadline        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    mark            DOUBLE PRECISION,
    file_id         VARCHAR(255)                            NOT NULL,
    temat_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_projekty PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.projekty_student CASCADE;
CREATE TABLE projekty.projekty_student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    projekt_id BIGINT                                  NOT NULL,
    student_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_projekty_student PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.role CASCADE;
CREATE TABLE projekty.role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.studenci CASCADE;
CREATE TABLE projekty.studenci
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    surname  VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    nr_album VARCHAR(255)                            NOT NULL,
    login_id BIGINT,
    CONSTRAINT pk_studenci PRIMARY KEY (id)
);

DROP TABLE IF EXISTS projekty.tematy CASCADE;
CREATE TABLE projekty.tematy
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    is_reserved BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tematy PRIMARY KEY (id)
);

ALTER TABLE projekty.login
    ADD CONSTRAINT uc_c14c098c82a9f5647aa3c5491 UNIQUE (username);

ALTER TABLE projekty.login
    ADD CONSTRAINT uc_e19e039cac26a4f8aaa2699d1 UNIQUE (email);

ALTER TABLE projekty.login
    ADD CONSTRAINT uc_login_id UNIQUE (id);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT uc_projekty_id UNIQUE (id);

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT uc_projekty_student_id UNIQUE (id);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_email UNIQUE (email);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_id UNIQUE (id);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_nralbum UNIQUE (nr_album);

ALTER TABLE projekty.tematy
    ADD CONSTRAINT uc_tematy_id UNIQUE (id);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT FK_PROJEKTY_ON_FILE FOREIGN KEY (file_id) REFERENCES projekty.pliki (id);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT FK_PROJEKTY_ON_TEMAT FOREIGN KEY (temat_id) REFERENCES projekty.tematy (id);

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT FK_PROJEKTY_STUDENT_ON_PROJEKTID FOREIGN KEY (projekt_id) REFERENCES projekty.projekty (id);

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT FK_PROJEKTY_STUDENT_ON_STUDENTID FOREIGN KEY (student_id) REFERENCES projekty.studenci (id);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT FK_STUDENCI_ON_LOGIN FOREIGN KEY (login_id) REFERENCES projekty.login (id);

ALTER TABLE projekty.login_roles
    ADD CONSTRAINT fk_logrol_on_login FOREIGN KEY (login_id) REFERENCES projekty.login (id);

ALTER TABLE projekty.login_roles
    ADD CONSTRAINT fk_logrol_on_role FOREIGN KEY (role_id) REFERENCES projekty.role (id);