CREATE TABLE projekty.projekty
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submission_date TIMESTAMP WITHOUT TIME ZONE,
    deadline        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    mark            DOUBLE PRECISION,
    CONSTRAINT pk_projekty PRIMARY KEY (id)
);

CREATE TABLE projekty.studenci
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    surname  VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    nr_album VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_studenci PRIMARY KEY (id)
);

CREATE TABLE projekty.tematy
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    is_reserved BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tematy PRIMARY KEY (id)
);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT uc_projekty_id UNIQUE (id);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_email UNIQUE (email);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_id UNIQUE (id);

ALTER TABLE projekty.studenci
    ADD CONSTRAINT uc_studenci_nralbum UNIQUE (nr_album);

ALTER TABLE projekty.tematy
    ADD CONSTRAINT uc_tematy_id UNIQUE (id);

DROP TABLE pliki CASCADE;

DROP TABLE projekty CASCADE;

DROP TABLE studenci CASCADE;

DROP TABLE tematy CASCADE;