CREATE TABLE projekty.projekty_student
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    projekt_id BIGINT                                  NOT NULL,
    student_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_projekty_student PRIMARY KEY (id)
);

ALTER TABLE projekty.projekty
    ADD file_id VARCHAR(255);

ALTER TABLE projekty.projekty
    ADD temat_id BIGINT;

ALTER TABLE projekty.projekty
    ALTER COLUMN file_id SET NOT NULL;

ALTER TABLE projekty.projekty
    ALTER COLUMN temat_id SET NOT NULL;

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT uc_projekty_student_id UNIQUE (id);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT FK_PROJEKTY_ON_FILE FOREIGN KEY (file_id) REFERENCES projekty.pliki (id);

ALTER TABLE projekty.projekty
    ADD CONSTRAINT FK_PROJEKTY_ON_TEMAT FOREIGN KEY (temat_id) REFERENCES projekty.tematy (id);

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT FK_PROJEKTY_STUDENT_ON_PROJEKTID FOREIGN KEY (projekt_id) REFERENCES projekty.projekty (id);

ALTER TABLE projekty.projekty_student
    ADD CONSTRAINT FK_PROJEKTY_STUDENT_ON_STUDENTID FOREIGN KEY (student_id) REFERENCES projekty.studenci (id);